feat: allow id only reference searches when valid
awslabs/fhir-works-on-aws-search-es pull request #107
Opened 2021-08-25 21:25 UTC by rsmayda

Issue #, if available: #106

FHIR spec:
> Some references may point to more than one type of resource; e.g. subject: Reference(Patient|Group|Device|..). In these cases, multiple resources may have the same logical identifier. Servers SHOULD reject a search where the logical id refers to more than one matching resource across different types. In order to allow the client to perform a search in these situations the type is specified explicitly

http://hl7.org/fhir/R4/search.html#reference

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-25 21:41 UTC, ssvegaraju approved these changes

2021-08-25 21:43 UTC, carvantes commented on src/QueryBuilder/typeQueries/referenceQuery.test.ts
> +        expect(referenceQuery(organizationParam, 'orgnaizationId', false, 'organization', ['Organization']))
typo `orgnaizationId`

2021-08-25 21:44 UTC, carvantes commented on src/QueryBuilder/typeQueries/referenceQuery.test.ts
> +            referenceQuery(organizationParam, 'orgnaizationId', false, 'organization', ['Organization', 'Group']),
typo `orgnaizationId`

2021-08-25 21:45 UTC, carvantes commented on src/QueryBuilder/typeQueries/referenceQuery.test.ts
> +        expect(() => referenceQuery(organizationParam, 'orgnaizationId', false, 'organization')).toThrow(
typo `orgnaizationId`

2021-08-25 21:56 UTC, carvantes commented on src/QueryBuilder/typeQueries/referenceQuery.ts
> +                `'${searchParamName}' is invalid please specify the resource type with the id`,
I think that the error message is hard to understand if you don't know the FHIR spec beforehand.
Maybe it's clearer w something like
```
`'${searchParamName}' is invalid please specify the reference value with the format [resourcetType]/[id] or as an absolute URL`

```

2021-08-25 21:59 UTC, carvantes approved these changes
looks good. 

Only minor comments related to typos and text messages.

2021-08-26 23:14 UTC, carvantes requested changes

2021-08-26 23:14 UTC, carvantes commented on src/QueryBuilder/typeQueries/referenceQuery.ts
> +        }
I think this is no longer the correct error msg. 
Looks like if `target.length === 0` then there's something wrong with the conpiler (or the FHIR definitions)

2021-08-26 23:14 UTC, carvantes commented on src/QueryBuilder/typeQueries/referenceQuery.test.ts
> +        expect(referenceQuery(organizationParam, 'http://fhir.com/baseR4/Organization/111', false, 'organization'))
can we move this to a separate test? something like "search for full URL".
I think that it's an important case that deserves it's own test.

2021-08-27 14:14 UTC, rsmayda commented on src/QueryBuilder/typeQueries/referenceQuery.ts
> +        }
Agreed. I am in favor of still throwing a `InvalidSearchParameterError` instead of a `InternalServerError`, to unblock the requester and give them advice on how to continue searching. While logging an error for the system admins

2021-08-27 18:29 UTC, carvantes commented on src/QueryBuilder/typeQueries/referenceQuery.ts
> +        }
I agree. 

It'll be a bit weird for the customer if the search query was correct, but FWoA is missing the target values. But that should be a very rare case anyways.

We should also at some point add validation on the compiler to ensure that reference parameters have at least one target.

2021-08-27 18:29 UTC, carvantes approved these changes

2021-08-27 18:30 UTC, merged