feat: add support for exact search modifier
awslabs/fhir-works-on-aws-search-es pull request #108
Opened 2021-08-26 08:17 UTC by ssvegaraju

- feat: add support for exact search modifier
- feat: add implementation of 'exact' search modifier

Issue #, if available:

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-26 19:47 UTC, carvantes requested changes

2021-08-26 19:47 UTC, carvantes commented on src/QueryBuilder/typeQueries/stringQuery.ts
> +    const fields = [compiled.path, `${compiled.path}.*${keywordSuffix}`];
I think that this won't work as expected. for `:exact` we want to query exclusively `keyword` type fields. `compiled.path` in many cases is a `text` field

2021-08-26 19:47 UTC, carvantes commented on src/elasticSearchService.ts
> -
nit: try to avoid this format changes. They just make the PRs bigger for no good reason

2021-08-26 19:47 UTC, carvantes commented on src/QueryBuilder/searchModifiers.ts
> +    Error = 'error',
Where is this used? It's probably better to throw an exception instead

2021-08-26 19:47 UTC, carvantes commented on src/QueryBuilder/index.ts
> +            const unmodifiedParam = searchParameter.split(':')[0];
Modifiers parsing logic (such as `.split(':')[0];`) should be defined in a single place. Probably on `searchModifiers.ts`

2021-08-26 19:47 UTC, carvantes commented on src/QueryBuilder/index.ts
> +            }
I don't think we should conflate the `:exact` modifier with the `useKeywordSubFields` param.

We need to validate that `:exact` is used ONLY with search params of type `string`. Only `stringQuery` needs to know how to implement `:exact`(which is about using `keyword` fields)., whereas `useKeywordSubFields` is a more generic param that several query types use

2021-08-26 19:47 UTC, carvantes commented on src/QueryBuilder/searchModifiers.ts
> +const getSearchModifiers = (searchParameter: string): SearchModifier => {
consider having this function return the param name as well
```ts
{
  searchParameterName: string,
  modifier?: string,
}
```

also nit: maybe rename to `parseSearchModifiers`

2021-08-26 19:47 UTC, carvantes commented on src/QueryBuilder/typeQueries/stringQuery.ts
> +export function stringQuery(compiled: CompiledSearchParam, value: string, useKeywordSubFields: boolean): any {
I think that we should update `stringQuery` (and all the other `somethingQuery`) to take a `modifier` parameter.

Then each method can be responsible of ensuring that the modifier is applicable to the search param type and of implementing it.

2021-08-26 19:49 UTC, carvantes commented
btw, rename the PR to be semantic. Note the extra `- ` before `feat`.

In theory the only thing that matters is the commit message when doing squash and merge, but it defaults to the PR name and it's easy to miss updating it later

2021-08-26 19:53 UTC, carvantes commented on src/__snapshots__/elasticSearchService.test.ts.snap
> +                    "name.*.keyword",
Maybe I'm missing something, but looks like all the extra `.keyword` on snapshots are actually breaking the tests.  The search query is not using `:exact` so it shouldn't append `.keyword`

2021-08-30 18:33 UTC, ssvegaraju commented on src/QueryBuilder/typeQueries/stringQuery.ts
> +    const fields = [compiled.path, `${compiled.path}.*${keywordSuffix}`];
I switched where we use the keyword subfield and it appears to work as expected, for example, in failing to find results on case mismatch.

2021-08-30 18:33 UTC, ssvegaraju commented on src/elasticSearchService.ts
> -
Got it, will keep that in mind going forward!

2021-08-30 18:34 UTC, ssvegaraju commented on src/QueryBuilder/searchModifiers.ts
> +    Error = 'error',
I replaced this enum with the return object you suggested in a different message.

2021-08-30 18:35 UTC, ssvegaraju commented on src/QueryBuilder/index.ts
> +            const unmodifiedParam = searchParameter.split(':')[0];
All of the parsing logic is now encapsulated in `parseSearchModifiers`

2021-08-30 18:35 UTC, ssvegaraju commented on src/QueryBuilder/index.ts
> +            }
This makes complete sense, I confused myself into thinking keyword sub-fields involved this parameter. This has been changed to simply use a new parameter instead.

2021-08-30 18:36 UTC, ssvegaraju commented on src/QueryBuilder/searchModifiers.ts
> +const getSearchModifiers = (searchParameter: string): SearchModifier => {
changed the return type and renamed the function!

2021-08-30 18:37 UTC, ssvegaraju commented on src/QueryBuilder/typeQueries/stringQuery.ts
> +export function stringQuery(compiled: CompiledSearchParam, value: string, useKeywordSubFields: boolean): any {
I've updated all the query types to ensure that the given modifier is valid for the type of query (in this case, exact is only applicable to string queries).

2021-08-30 18:38 UTC, ssvegaraju commented on src/__snapshots__/elasticSearchService.test.ts.snap
> +                    "name.*.keyword",
I restored the previously working snapshot in the latest commit, and made sure that all other tests pass even without a specified modifier and don't add anything to the output.

2021-08-30 19:48 UTC, carvantes requested changes

2021-08-30 19:48 UTC, carvantes commented on src/QueryBuilder/typeQueries/stringQuery.ts
> +
We should throw an error if the modifier is something other than `exact`

2021-08-30 19:48 UTC, carvantes commented on src/QueryBuilder/typeQueries/dateQuery.ts
> +    }
We should "flip" this validation logic. Right now we'd need to update the validation rules in ALL queries when we add a new modifier. It would be simpler to have something like `const SUPPORTED_MODIFIERS = []` and use it for validation. 
Then for new modifiers we just need to modify the queries that actually support them.
Same goes for all other typeQueries files

2021-08-30 19:48 UTC, carvantes commented on src/QueryBuilder/searchModifiers.ts
> +    }
I think that we can remove this validation. The thing is that the full validation requires knowing the type of the search parameter to check if the modifier is applicable to that type and that is done on the typeQueries. This partial validation feels redundant.

2021-08-30 21:07 UTC, ssvegaraju commented on src/QueryBuilder/typeQueries/stringQuery.ts
> +
Good catch, I updated this as well as all the other queries to utilize the `SUPPORTED_MODIFIERS` `const` to check if a modifier is valid.

2021-08-30 21:07 UTC, ssvegaraju commented on src/QueryBuilder/searchModifiers.ts
> +    }
That makes sense to me, I've gone ahead and removed it.

2021-08-30 21:08 UTC, ssvegaraju commented on src/QueryBuilder/typeQueries/dateQuery.ts
> +    }
Redid the validation logic according to this suggestion, makes much more sense than the branching if-else that I had previously.

2021-08-31 07:41 UTC, carvantes requested changes

2021-08-31 07:41 UTC, carvantes commented on src/QueryBuilder/typeQueries/stringQuery.test.ts
> +                "name.*",
I think this is not working as intended, it should query `name.*.keyword`, otherwise it may include text fields

This was correct on a previous version. Related to https://github.com/awslabs/fhir-works-on-aws-search-es/pull/108#discussion_r696906778

2021-08-31 08:08 UTC, ssvegaraju commented on src/QueryBuilder/typeQueries/stringQuery.test.ts
> +                "name.*",
I see, I think I misunderstood the comment but I've restored the correct functionality in the latest commit.

2021-08-31 15:09 UTC, carvantes commented on src/QueryBuilder/typeQueries/stringQuery.test.ts
> +                "name.*",
Last commit is not correct yet. **Both** fields must end in `.keyword`. (`"name.keyword"`, `"name.*.keyword"`)

2021-08-31 15:13 UTC, ssvegaraju commented on src/QueryBuilder/typeQueries/stringQuery.test.ts
> +                "name.*",
Got it, fixed that in the latest commit

2021-08-31 19:03 UTC, carvantes approved these changes
🚀🚀🚀

2021-08-31 19:09 UTC, merged