Implement basic _include and _revinclude
awslabs/fhir-works-on-aws-search-es pull request #11
Opened 2020-09-11 13:29 UTC by carvantes

Description of changes:

_include and _revinclude allow to fetch related resources as part of search results.

For example:
```
GET [base]/MedicationRequest?_include=MedicationRequest:patient
GET [base]/MedicationRequest?_revinclude=Provenance:target
```
The first search requests all matching MedicationRequests, to include any patient that the medication prescriptions in the result set refer to. The second search requests all matching prescriptions, return all the provenance resources that refer to them. 

`_include` and `_revinclude` also support wildcards and have an `:iterate` variant, but those features are out of the scope of this PR

https://www.hl7.org/fhir/search.html

Also added missing unit tests. Elasticsearch queries are tough to validate without actually running them against an Elasticsearch instance so we are not making specific assertions on them but rather using snapshot testing.
Snapshots let us see what queries are run for the different search requests in test cases and serve as nice regression tests. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-09-11 14:43 UTC, rsmayda commented on src/__tests__/elasticSearchService.test.ts
> +        each([
@nguyen102 this seems like a cleaner approach for 'each' -- thoughts?

2020-09-11 14:50 UTC, rsmayda commented on src/__tests__/elasticSearchService.test.ts
> +            expect((ElasticSearch.search as jest.Mock).mock.calls).toMatchSnapshot();
What are we testing here? that the search result returned?

2020-09-11 14:50 UTC, rsmayda commented on src/elasticSearchService.ts
> +    SEARCH_PAGINATION_PARAMS.PAGES_OFFSET,
Does pagination still work when using rev/includes?

2020-09-11 14:56 UTC, rsmayda commented on src/elasticSearchService.ts
> +    SEARCH_PAGINATION_PARAMS.PAGES_OFFSET,
FYI from FHIR spec: 
`When search results are paged, each page of search results should include the matching includes for the resources in each page, so that each page stands alone as a coherent package.`

2020-09-11 15:44 UTC, carvantes commented on src/elasticSearchService.ts
> +    SEARCH_PAGINATION_PARAMS.PAGES_OFFSET,
yes, pagination works with rev/include. However, rev/include brings in additional resources that are outside the pagination count limit.

i.e. `[base]/MedicationRequest?_include=MedicationRequest:patient&_count=10` can return more than 10 resources. 10 MedicationRequest + all the related patients

2020-09-11 15:52 UTC, carvantes commented on src/__tests__/elasticSearchService.test.ts
> +            expect((ElasticSearch.search as jest.Mock).mock.calls).toMatchSnapshot();
It's testing that the executed ES queries match the ones in the snapshot. you can see the snapshots at `src/__tests__/__snapshots__/elasticSearchService.test.ts.snap`

2020-09-11 18:03 UTC, rsmayda commented on src/elasticSearchService.ts
> +    SEARCH_PAGINATION_PARAMS.PAGES_OFFSET,
Is that expected as per FHIR spec?

2020-09-11 18:55 UTC, nguyen102 commented on src/__tests__/elasticSearchService.test.ts
> +        each([
nice! I like this syntax

2020-09-11 18:55 UTC, nguyen102 commented on src/__tests__/elasticSearchService.test.ts
> +        ]).test('queryParams=%j', async (queryParams: any) => {
is the `j` supposed to be here? In `queryParams=%j`

2020-09-11 20:48 UTC, nguyen102 commented on src/elasticSearchService.ts
> +        const idsByResourceType = mapValues(
Nitpick: Is this a map of resourceType to ids? We've been using the format `keyToValue`. Rename the variable `idsByResourceType` => `resourceTypeToIds`

2020-09-11 20:50 UTC, nguyen102 commented on src/elasticSearchService.ts
> +        const resourcesToInclude = flatten(
What is an example value for this variable? Is this a map of ressources to the include variable?

2020-09-11 20:54 UTC, carvantes commented on src/__tests__/elasticSearchService.test.ts
> +        ]).test('queryParams=%j', async (queryParams: any) => {
yes, it's used for formatting. `%j` is for json so the text name looks as follows:
```
 typeSearch
    query snapshots for simple queryParams
      ✓ queryParams={} (5ms)
      ✓ queryParams={"_count":10,"_getpagesoffset":2} (2ms)

```

https://www.npmjs.com/package/jest-each

2020-09-11 21:04 UTC, carvantes commented on src/elasticSearchService.ts
> +        const resourcesToInclude = flatten(
It has type:
```
{resourceType: string, id: string}[]
```

2020-09-11 21:21 UTC, carvantes commented on src/elasticSearchService.ts
> +        const idsByResourceType = mapValues(
done

2020-09-11 21:22 UTC, carvantes commented on src/elasticSearchService.ts
> +        const resourcesToInclude = flatten(
I added the type explicitly. It makes it much more readable

2020-09-11 21:25 UTC, nguyen102 commented on src/elasticSearchService.ts
> +        const resourcesToInclude = flatten(
Ah ok. Thanks for the clarification. I think the naming of this variable is to indicate which resources to search for for `searchIncludes`, but it's a little confusing since when I first read it, I thought it was a map with key of resource and value of id. We've been using the syntax for variable name of `keyToValue`. Could we rename this to something like `resourceTypeToIdForIncludedResources`. It's kind of a long variable name, but I'm open to suggestions for other ideas.

2020-09-11 21:29 UTC, nguyen102 commented on src/elasticSearchService.ts
> +    private async processSearchIncludes(
I think some it might be helpful to move these private methods to a class like `elasticSearchServiceHelper` and then make those methods `public`. That way this will keep `elasticSearchService` smaller, and also allow us to unit tests these methods. 

There's a lot of variable mapping in this method, and it makes it a little hard to follow what each variable are as they're being transformed. Being able to unit tests this method and maybe even components of this methods would make it easier to understand what is going on.

2020-09-14 07:16 UTC, carvantes commented on src/elasticSearchService.ts
> +    SEARCH_PAGINATION_PARAMS.PAGES_OFFSET,
yes,
> Note that the Bundle.total only include the total number of matching resources. It does not count extra resources such as OperationOutcome or included resources that may also be returned

2020-09-16 18:15 UTC, carvantes commented on src/elasticSearchService.ts
> +    private async processSearchIncludes(
I split it into functions and moved it to a separate file.

2020-09-16 18:22 UTC, carvantes commented on src/elasticSearchService.ts
> +        const resourcesToInclude = flatten(
Renamed to simply `resourceReferences`. Also I did some refactoring so this var is now on a smaller function so it's easier to understand.

btw, This is var involves objects, but they are not  as a map, so using `To` like in `resourceTypeToIdForIncludedResources ` does not really apply.
i.e:
```
[
  { resourceType: 'Practitioner', id: '111' },
  { resourceType: 'Organization', id: '222' },
]
```

2020-09-16 19:26 UTC, nguyen102 commented on src/searchInclusions.ts
> +    const { sourceResource, searchParameter, targetResourceType } = match.groups!;
Ooo, interesting. What does `!` in `match.groups` do?

2020-09-16 19:37 UTC, carvantes commented on src/searchInclusions.ts
> +    const { sourceResource, searchParameter, targetResourceType } = match.groups!;
It's called Non-null assertion operator, https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator

It is safe to use it here since we've already tested that `match` is not null and we know for sure that `groups` is not null because the regex has capture groups.

2020-09-16 19:51 UTC, nguyen102 requested changes
Overall looks good. Just one nitpick. Our current test convention is to put the test file next to the file being tested. For example. https://github.com/awslabs/fhir-works-on-aws-routing/tree/mainline/src/router/handlers

So if we can just keep the consistent with the tests here..

2020-09-16 19:51 UTC, nguyen102 commented on src/__tests__/SearchInclusions.test.ts
> +describe('getInclusionParametersFromQueryParams', () => {
Thanks for adding these tests! They make it a lot easier to understand what the input and output of the functions under test are.

2020-09-16 20:44 UTC, carvantes commented
> Overall looks good. Just one nitpick. Our current test convention is to put the test file next to the file being tested. For example. https://github.com/awslabs/fhir-works-on-aws-routing/tree/mainline/src/router/handlers
> 
> So if we can just keep the consistent with the tests here.

Done

2020-09-16 20:44 UTC, nguyen102 approved these changes

2020-09-17 01:30 UTC, rsmayda commented on package.json
> +    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$"
may want to revert?

2020-09-17 01:30 UTC, rsmayda commented on src/SearchInclusions.test.ts
> +import each from 'jest-each';
nit: filename between test and non test has a casing difference. make this file name with a lowercase 's'

2020-09-17 01:30 UTC, rsmayda commented on src/elasticSearchService.ts
> +            ]);
It looks like in this method we are querying ES for includes/revincludes even when it is not in the query -- is that right? Actually looking at searchInclusions.ts you have a helper method that will return an empty array which in turn will make no queries ran.. 

^^ Please confirm this :)

2020-09-17 02:15 UTC, carvantes commented on package.json
> +    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$"
Done. Although it did require a minor change to `.test.ts$` in order to exclude test snapshot files.

2020-09-17 02:16 UTC, carvantes commented on src/SearchInclusions.test.ts
> +import each from 'jest-each';
done

2020-09-17 02:41 UTC, carvantes commented on src/elasticSearchService.ts
> +            ]);
That's correct. 

These methods always run but may end up not executing any ES queries and just returning an empty array.

2020-09-17 13:54 UTC, rsmayda approved these changes

2020-09-18 03:14 UTC, merged