fix: update IG validation to reject reference params with no target
awslabs/fhir-works-on-aws-search-es pull request #123
Opened 2021-09-22 20:32 UTC by ssvegaraju

Issue #, if available:
[#449](https://github.com/awslabs/fhir-works-on-aws-deployment/issues/449)
Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-22 23:32 UTC, carvantes requested changes

2021-09-22 23:32 UTC, carvantes commented on src/implementationGuides/index.test.ts
> +    test(`search param of type reference with no target`, async () => {
Add a test for target being an empty array. I think a code change is needed to handle that case properly

2021-09-22 23:39 UTC, carvantes commented
Also, the error msg of `Error: The following input is not a search parameter: {...}` is not that helpful. The `isFhirSearchParam` is a very basic check to make sure that required fields are present and that the field types are correct. 

Maybe we can create a separate method for semantic validations like this that throws more specific error messages.

2021-09-23 03:19 UTC, ssvegaraju commented on src/implementationGuides/index.test.ts
> +    test(`search param of type reference with no target`, async () => {
Good catch, I added a test case for this!

2021-09-23 17:33 UTC, carvantes approved these changes

2021-09-23 17:56 UTC, merged