feat: enable chained parameters in search
awslabs/fhir-works-on-aws-search-es pull request #129
Opened 2021-10-25 01:21 UTC by Bingjiling

Issue #, if available:

Description of changes:

Enable chained parameters in search. 

The chained parameters are process in the following steps: 

1. Verify the chained parameters are valid - chained parameter should point to a valid resource type reference, if there're multiple valid resource types, a single resource type should be specified in search modifier. Chained parameter should return less than 100 hits. 
2. For each chained parameters, search through the chain to get the values used for the main search. e.g.: For ```{{API_URL}}/Patient?general-practitioner:PractitionerRole.location:Location.address-city=NYC``` , we'll search for `Location` whose address-city is NYC(result in `Location/1234`), then search for `PractitionerRole` whose location is Location/1234(result in `PractitionerRole/5678`).
3. Combine results from all chained parameters in a SHOULD(OR) clause
4. Insert it into the "main" search parameters  

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-10-25 05:21 UTC, carvantes requested changes
Please fix first all the lint errors. Otherwise it is hard to review the code.

btw, the eslint version for FWoA packages was recently updated, maybe that's what caused the issue. Make sure that you are using the correct eslint version on your end.

2021-10-25 17:53 UTC, Bingjiling commented on src/QueryBuilder/index.ts
> +            return { chain: organizedChain, searchQuery: { [initialSearchParam]: searchValues } };
For `{{API_URL}}/Patient?general-practitioner:PractitionerRole.location.address-city=NYC`, it will return 
```
{
chain: [general-practitioner:PractitionerRole, location:Location]
searchQuery: 
  {
  address-city: 'NYC'
  }
}
```

2021-10-25 18:08 UTC, Bingjiling commented on src/elasticSearchService.ts
> +        return combinedChainedParameters;
For `{{API_URL}}/Patient?general-practitioner:PractitionerRole.location:Location.address-city=NYC&organization.name=someName`, it will return
```
{
  'general-practitioner': [ 'PractitionerRole/some-uuid-the-chain-point-to' ],
  organization: [ 'Organization/some-uuid-the-chain-point-to' ]
}
```

2021-10-25 21:04 UTC, carvantes requested changes

2021-10-25 21:04 UTC, carvantes commented on src/elasticSearchService.ts
> +                const stepReqeust: TypeSearchRequest = { ...request, resourceType, queryParams: stepQueryParams };
typo `stepReqeust `

2021-10-25 21:04 UTC, carvantes commented on src/QueryBuilder/index.ts
> +            return { chain: organizedChain, searchQuery: { [initialSearchParam]: searchValues } };
IMO this structure is not that great as a return value since the `getChainedParametersQuery` method (the only caller of `getOrganizedChainedParameters`) needs to do significant manipulation of this structure before being able to use it for queries.
 
It'd be better to concentrate the parsing logic here and return something that almost maps 1:1 to the query args we need.
Maybe something like: 
```
{
  initialValue: 'NYC',
  chain: [
    {
      resourceType: 'Location',
      searchParam: 'address-city',
    }, 
    {
      resourceType: 'PractitionerRole',
      searchParam: 'location',
    }, 
    {
      resourceType: 'Patient',
      searchParam: 'general-practitioner',
    }
  ]
}
```

2021-10-25 21:04 UTC, carvantes commented on src/QueryBuilder/index.ts
> +export const getOrganizedChainedParameters = (
nit: rename to `parseChainedParameters`. I think that "parsing" is descriptive of what this method is doing.

---

Also, can you move this method to a separate file and add unit tests for it? Similar to `sort.ts`

2021-10-25 21:04 UTC, carvantes commented on src/QueryBuilder/index.ts
> +): any => {
Do not use `any`, use the concrete type here.
Sometimes you can have implicit types, but in my experience specifying explicitly the return type of functions improves readability by a LOT.

btw, maybe your IDE can auto generate this. In Webstorm it is alt+enter and then "specify type explicitly"

2021-10-25 21:04 UTC, carvantes commented on src/QueryBuilder/searchModifiers.ts
> +    }
idk why the `toLowerCase` was there in the first place. Maybe we can just get rid of it instead of adding an extra param

2021-10-25 21:04 UTC, carvantes commented on src/elasticSearchService.ts
> +    private async getChainedParametersQuery(request: TypeSearchRequest, filters: any[] = []) {
Specify the return type of this function explicitly

2021-10-25 21:04 UTC, carvantes commented on src/elasticSearchService.ts
> +                };
use the `fields` parameter so that you only retrieve the `id` field of the matching documents. That should be faster than transmitting the entire documents.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html

2021-10-27 14:21 UTC, Bingjiling commented on src/QueryBuilder/searchModifiers.ts
> +    }
Sure,  I double checked where it's used, it should be fine.

2021-10-28 18:08 UTC, rsmayda commented on src/QueryBuilder/chain.ts
> +                        `Chained search parameter '${searchModifier.parameterName}' for resource type ${currentResourceType} does not point to another resource.`,
```suggestion
                        `Chained search parameter '${searchModifier.parameterName}' for resource type ${currentResourceType} is not a reference.`,
```

2021-10-28 18:19 UTC, rsmayda commented on src/QueryBuilder/util.ts
> +    return parameterKey.match('[A-Za-z][.][A-Za-z]');
`GET Patient?general-practitioner.name=Joe&general-practitioner.address-state=MN`

This regex does work for this chain

2021-10-28 18:23 UTC, rsmayda commented on src/elasticSearchService.ts
> +    // Return translated chained parameters that can be used as normal search parameters
Do we follow the below guidance? 

> Note that chained parameters are applied independently to the target resource. For example,
`GET Patient?general-practitioner.name=Joe&general-practitioner.address-state=MN`
may return Patients cared for by Joe from CA and Jane from MN: no one practitioner need satisfy both conditions. E.g. the chains are evaluated separately.

https://www.hl7.org/fhir/search.html#chaining

2021-10-28 18:24 UTC, rsmayda commented on src/elasticSearchService.ts
> +    // Return translated chained parameters that can be used as normal search parameters
We should add this as a integ test case

2021-10-28 18:25 UTC, rsmayda commented on src/constants.ts
> +export const MAX_CHAINED_PARAMS_RESULT: number = 100;
How would we reach this max, like if some one creates a chain 100 long? NVM I understand more at the bottom

2021-10-28 18:36 UTC, rsmayda commented on src/elasticSearchService.ts
> +    private async getChainedParametersQuery(request: TypeSearchRequest, filters: any[] = []): Promise<{}> {
How does pagination work with chainedParams?

2021-10-28 18:44 UTC, Bingjiling commented on src/QueryBuilder/util.ts
> +    return parameterKey.match('[A-Za-z][.][A-Za-z]');
Emm it can match the `r.n` and `r.a` part for the two parameters right?

2021-10-28 18:50 UTC, Bingjiling commented on src/elasticSearchService.ts
> +    // Return translated chained parameters that can be used as normal search parameters
Yes, we follow the guidance by pushing all chained parameters into a SHOULD(OR) clause when assembling it for the final search query. This scenario is covered by unit test [here](https://github.com/awslabs/fhir-works-on-aws-search-es/pull/129/files#diff-baee28b2589ad3c7198a737b611fd836b6c07600a53b7340e2d32eb7869f9704R994-R997)

2021-10-28 18:56 UTC, Bingjiling commented on src/elasticSearchService.ts
> +    private async getChainedParametersQuery(request: TypeSearchRequest, filters: any[] = []): Promise<{}> {
While searching recursively to 'unchain' the parameters for the main search, we ask for only 100 records and check for the total hits. If total hits is larger than 100, then it fails, if not, then we used the retrieved records to move forward.

2021-10-28 19:32 UTC, carvantes requested changes

2021-10-28 19:32 UTC, carvantes commented on src/elasticSearchService.ts
> +                            fields: ['id'],
Looks like you need to add `"_source": false` as well. Otherwise you are still getting the entire resource document.

2021-10-29 00:52 UTC, rsmayda commented on src/QueryBuilder/util.ts
> +    return parameterKey.match('[A-Za-z][.][A-Za-z]');
Ooo gotcha I misunderstood what you were using `match` for it looks like it is just a boolean check -- if so could we use `test` instead:
https://stackoverflow.com/questions/10940137/regex-test-v-s-string-match-to-know-if-a-string-matches-a-regular-expression

2021-10-29 00:54 UTC, rsmayda commented on src/elasticSearchService.ts
> +    private async getChainedParametersQuery(request: TypeSearchRequest, filters: any[] = []): Promise<{}> {
Does pagination work for the entire query itself? i.e. a chained search returns 50 Patients on floor 5 our paging defaults to only return 20 at a time. Can a user use paging token to get the remaining 30?

2021-11-01 13:55 UTC, Bingjiling commented on src/elasticSearchService.ts
> +    private async getChainedParametersQuery(request: TypeSearchRequest, filters: any[] = []): Promise<{}> {
Yes, once the entire query is assembled, it works the same way as before with a query that is a bit more complicated. Without chained parameter, the entire query looks like: 
```
bool: {
            filter: additionalFilters,
            must: [mustCondition1, mustCondition2 .....],
        }
``` 

With chained parameter, the query looks like: 
```
bool: {
            filter: additionalFilters,
            must: [
               bool: {
                  should: [chainParamCondition1, chainParamCondition2]
                  }
                  mustCondition1, 
                  mustCondition2 .....],
        }
```

2021-11-01 14:52 UTC, rsmayda commented on src/elasticSearchService.test.ts
>                                  _source: {
Since we are only using `_fields` now do we need this `_source` in our tests? Which return is more accurate from a raw ES search?

2021-11-01 19:42 UTC, carvantes reviewed
Can you also update the README at: 
https://github.com/awslabs/fhir-works-on-aws-search-es/blob/mainline/README.md?plain=1#L102

On the Notes column you can mention any limitations we imposed (e.g. the 100 limit thing)

2021-11-02 16:10 UTC, Bingjiling commented on src/elasticSearchService.test.ts
>                                  _source: {
It's still needed for the 'main' search to run, which use the `_source` filed. We can use mockOnce many times to have different data returned, but it's a bit of an overkill.

2021-11-02 20:26 UTC, carvantes approved these changes

2021-11-02 21:10 UTC, merged