fix: nonsense chained values return empty
awslabs/fhir-works-on-aws-search-es pull request #139
Opened 2021-11-10 20:21 UTC by ssvegaraju

Issue #138, if available:

Description of changes:
Update chain param search to no longer return all resources when presented with a nonsense search parameter.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-10 22:39 UTC, carvantes requested changes

2021-11-10 22:39 UTC, carvantes commented on src/__snapshots__/elasticSearchService.test.ts.snap
> +            ],
I think that this query will still match ALL documents.

How was this tested?

2021-11-10 22:39 UTC, carvantes commented on src/elasticSearchService.test.ts
> +    describe('query snapshots for nonsense chained queryParams', () => {
Avoid using `nonsense` here. Be specific. Maybe something like "chained parameters with zero matches".

Also, rename the PR.

2021-11-11 14:44 UTC, Bingjiling commented on src/elasticSearchService.test.ts
> +                            value: 1,
Should the total hits be 0 if there's no match?

2021-11-11 18:14 UTC, ssvegaraju commented on src/elasticSearchService.test.ts
> +    describe('query snapshots for nonsense chained queryParams', () => {
Renamed PR and tests.

2021-11-11 18:15 UTC, ssvegaraju commented on src/__snapshots__/elasticSearchService.test.ts.snap
> +            ],
Looks like there was a bug in the error catching logic that was failing test (and I also had a 1 instead of a 0 in the test).

2021-11-11 18:15 UTC, ssvegaraju commented on src/elasticSearchService.test.ts
> +                            value: 1,
This should be a 0, yes! Also, looks like there was an issue with the index errors not properly being filtered, which should be fixed now.

2021-11-11 19:50 UTC, carvantes commented on src/elasticSearchService.ts
> +            if (parsedChainParameters.length > 0) {
Maybe I'm missng something, but I don't see the point of calling `parseChainedParameters` here.

The if `parsedChainParameters.length > 0` check is redundant. When there are no matches the next if `isEmpty(chainedParameterQuery)` will always be true.

It's probably better to revert `getChainedParametersQuery` to accepting `request: TypeSearchRequest` as param. It's simpler.

2021-11-11 19:51 UTC, carvantes commented
What happens for `GET /DetectedIssue?patient:Patient.name=`?

2021-11-11 20:57 UTC, ssvegaraju commented
> 
> 
> What happens for `GET /DetectedIssue?patient:Patient.name=`?

This returns a bundle of all detected issues with a Patient field. This is similar to the behavior of `GET /Patient?name=` returning a bundle of all Patients.

2021-11-11 21:01 UTC, ssvegaraju commented on src/elasticSearchService.ts
> +            if (parsedChainParameters.length > 0) {
The reason we had to do it this way is in case a search is made without any chained parameters, in which case the search would just return empty without the check for parsedChainParameters.

2021-11-12 18:24 UTC, carvantes approved these changes

2021-11-12 20:33 UTC, merged