[WIP] fix: boolean token search
awslabs/fhir-works-on-aws-search-es pull request #145
Opened 2021-12-07 17:57 UTC by Bingjiling

Issue #, if available:

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-07 18:14 UTC, rsmayda requested changes

2021-12-07 18:14 UTC, rsmayda commented on src/QueryBuilder/typeQueries/tokenQuery.test.ts
> +                        "identifier",
Duplicate `identifier` is that right?

2021-12-07 18:14 UTC, rsmayda commented on src/QueryBuilder/typeQueries/tokenQuery.ts
> +            `${compiled.path}`, // boolean
So we don't want this. Just having `compiled.path` in the array list means it could become a text search, meaning searching 'male' could return both 'female' and 'male'.

Based on the `CompiledSearchParam` is there anyway for us to know if a param is a bool or not?

2021-12-07 18:15 UTC, rsmayda reviewed
Also could we add a integ test for this exact use case?

2021-12-07 19:08 UTC, Bingjiling commented on src/QueryBuilder/typeQueries/tokenQuery.ts
> +            `${compiled.path}`, // boolean
Emmm I'm not getting this one. I tested searching for `gender=female` after this change and it is returning only female records. Compiled search parameter only gives information on the path like `{ resourceType: 'Patient', path: 'gender' }` and `{ resourceType: 'Patient', path: 'active' }`

2021-12-07 20:20 UTC, Bingjiling commented on src/QueryBuilder/typeQueries/tokenQuery.test.ts
> +                        "identifier",
Removed duplicates

2021-12-07 21:42 UTC, Bingjiling commented on src/QueryBuilder/typeQueries/tokenQuery.ts
> +            `${compiled.path}`, // boolean
Update from earlier discussion: Searching for 'fe' returns no records, which is the expected behavior.

2021-12-08 20:59 UTC, carvantes submitted a review, later dismissed
Looks good. 

Please updated the description to link the GH issue # in the description. It's good for bookkeeping.

2021-12-08 20:59 UTC, carvantes commented on src/QueryBuilder/typeQueries/tokenQuery.ts
> +        // See https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html for more detail
nit: the comment feels outdated since we now use static mappings instead of dynmaic mappings

2021-12-08 21:10 UTC, Bingjiling commented on src/QueryBuilder/typeQueries/tokenQuery.ts
> +            `${compiled.path}`, // boolean
Update test cases: Searching for prefix with `-` or `:` separation returns no records 

Tests detail: Create a Patient resource with 

```
"communication": [
          {
            "language": {
              "coding": [
                {
                  "system": "urn:ietf:bcp:47",
                  "code": "es-en", or "es:en"
                  "display": "Spanish"
                }
              ],
              "text": "Spanish"
            }
          }
        ],
```

Search for `language=es` does not return the patients just created. Search for `language=es-en` or `language=es:en` returns the corresponding records.

2021-12-09 16:22 UTC, rsmayda approved these changes

2021-12-09 18:42 UTC, merged