chore: add logging for unsupported query params
awslabs/fhir-works-on-aws-search-es pull request #151
Opened 2021-12-17 10:46 UTC by ssvegaraju

Issue #, if available:
FHIR-223

Description of changes:
Rather than error out calls with these query params, I opted to create routing for these general parameters and simply place a log message that the query param is currently unsupported.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-17 16:57 UTC, Bingjiling commented on src/constants.ts
> +export const GENERAL_PARAMETERS = ['_format', '_pretty', '_summary', '_elements'];
Rename it to UNSUPPORTED_PARAMETERS?

2021-12-17 20:28 UTC, ssvegaraju commented on src/constants.ts
> +export const GENERAL_PARAMETERS = ['_format', '_pretty', '_summary', '_elements'];
I named it this based off the FHIR spec: https://www.hl7.org/fhir/http.html#parameters. Should I append UNSUPPORTED to the front instead?

2021-12-20 19:54 UTC, Bingjiling commented on src/constants.ts
> +export const GENERAL_PARAMETERS = ['_format', '_pretty', '_summary', '_elements'];
Yes, please. Appending UNSUPPORTED makes it more readable, or it might create confusion why GENERAL PARAMETERS were disregarded.

2022-01-12 08:08 UTC, carvantes requested changes
The proposed change sounds good to me. It makes sense for search requests like `/Provenance?_count=100&_pretty=true` to succeed instead of failing with `Invalid search parameter '_pretty' for resource type Provenance`. I'm ok with dropping the unsupported params and just logging them.

2022-01-12 08:08 UTC, carvantes commented on src/FhirQueryParser/index.ts
> +        }
I suggest moving this condition to the `.filter` above. It's a bit confusing to do filtering inside the `flatMap`

it may be better to wait for https://github.com/awslabs/fhir-works-on-aws-search-es/pull/155 to be merged since this PR will have small conflicts with it.

2022-01-12 19:32 UTC, ssvegaraju commented on src/FhirQueryParser/index.ts
> +        }
That makes sense. I also fixed the merge conflicts and updated the PR 👍

2022-01-12 20:20 UTC, carvantes commented on src/constants.ts
> +export const UNSUPPORTED_GENERAL_PARAMETERS = ['_format', '_pretty', '_summary', '_elements'];
I think that we need to add `...UNSUPPORTED_GENERAL_PARAMETERS` to the `NON_SEARCHABLE_PARAMETERS` array above(btw ,`_format` is still there).

right now `NON_SEARCHABLE_PARAMETERS` is used in other parts of the code, not just in the parser.

2022-01-12 20:20 UTC, carvantes commented on src/FhirQueryParser/index.ts
> +
Let's add those params to `otherParams`

2022-01-13 23:25 UTC, ssvegaraju commented on src/constants.ts
> +export const UNSUPPORTED_GENERAL_PARAMETERS = ['_format', '_pretty', '_summary', '_elements'];
Added the Unsupported general params array to the non searchable array, and removed _format (probably missed from resolving the merge conflicts), thanks for catching that!

2022-01-14 06:53 UTC, carvantes requested changes

2022-01-14 06:53 UTC, carvantes commented on src/FhirQueryParser/index.ts
> +            if (UNSUPPORTED_GENERAL_PARAMETERS.includes(searchParameter)) {
with the latest changes this condition needs to be moved before the `if(NON_SEARCHABLE_PARAMETERS.includes(searchParameter)) {`at L200. Otherwise this code is unreachable.

2022-01-14 07:07 UTC, ssvegaraju commented on src/FhirQueryParser/index.ts
> +            if (UNSUPPORTED_GENERAL_PARAMETERS.includes(searchParameter)) {
Thank you for catching that. Just updated it.

2022-01-18 06:10 UTC, carvantes approved these changes

2022-01-18 08:04 UTC, merged