feat: add method validateSubscriptionSearchCriteria
awslabs/fhir-works-on-aws-search-es pull request #153
Opened 2022-01-10 18:44 UTC by Bingjiling

Issue #, if available:

Description of changes:

* Add method validateSubscriptionSearchCriteria 
* Update/Add unit tests 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-10 22:35 UTC, carvantes requested changes

2022-01-10 22:35 UTC, carvantes commented on src/FhirQueryParser/index.ts
> +        hasUnsearchableParams: size(normalizedQueryParams) > searchableParams.length,
I think that this does not belong here. I think it's best to avoid having subscription-specific logic on the parser.

It's not necessarily true that this params are "unsearchable". They may searchable, but just not usable in subscriptions due to their complexity. I'd suggest moving this check outside of this method.

2022-01-10 22:35 UTC, carvantes commented on src/elasticSearchService.test.ts
> +            }).toBeDefined();
This assertion is not really doing anything. `validateSubscriptionSearchCriteria` is not being called. `expect` is just asserting that the arrow function is defined.

e.g. this passes:
```
expect(() => { throw new Error(); }).toBeDefined();
```
 use `expect().not.toThrow()` instead

2022-01-10 22:35 UTC, carvantes commented on src/elasticSearchService.ts
> +        const queryString = queryStrings.join('?');
I think we can clean up this a little bit. `queryStrings` is not truly query strings. It may be just a bunch of text fragments since `?` beyond the first are taken literally as strings . (e.g. `Patient?name=Anne?as?&phone=333?222`)

code would be easier to follow if you find the index of the first `?` and then slice on it.

Also, can you add a unit test with multiple `?` on the query params?

2022-01-11 20:17 UTC, Bingjiling commented on src/FhirQueryParser/index.ts
> +        hasUnsearchableParams: size(normalizedQueryParams) > searchableParams.length,
Yes, I agree subscription logic should not interfere with existing search logic as much as possible. I tried doing it outside of this method first, but it turns out to be messy as we'll be picking apart the `parseQuery` function to give the "interim result" needed by the validation. I think this way is actually less destruction with the parser function instead of breaking it into multiple pieces. 

I can update the parameter name to be `hasUnsearchableOrChainedParams`?

2022-01-11 20:17 UTC, Bingjiling commented on src/elasticSearchService.test.ts
> +            }).toBeDefined();
Good catch!

2022-01-12 07:53 UTC, carvantes commented on src/FhirQueryParser/index.ts
> +        hasUnsearchableParams: size(normalizedQueryParams) > searchableParams.length,
I think that we should strive to keep the parser clean. We can improve the parser to make this easier though. Take a look at https://github.com/awslabs/fhir-works-on-aws-search-es/pull/155
Once we merge that PR you can validate the subscription outside of the parser by checking that 
`parsed.inclusionSearchParams`, `parsed.chainedSearchParams` and `parsed.otherParams` are all empty.

2022-01-18 19:36 UTC, carvantes reviewed
Looking good. 

I think that we should support the case of subscribing to changes on ANY resource of a given resourceType. e.g. the criteria for ALL patients would be `Patient` or `Patient?`. 

It looks like you only need some minor changes in parsing (`?` may not be mandatory) to support this case.

2022-01-18 19:36 UTC, carvantes commented on src/FhirQueryParser/index.test.ts
> +            _include: 'Patient:someField',
are the changes in this test file necessary?

We already have dedicated tests for chained, inclusion and other params near the end of this file. They are not wrong, but I think it's confusing to add something like an `_include` param here when this test is meant to be focused on the `date` params.

2022-01-20 20:39 UTC, carvantes approved these changes

2022-01-20 20:50 UTC, merged