fix: multisearch should return >10 queries
awslabs/fhir-works-on-aws-search-es pull request #164
Opened 2022-01-31 18:57 UTC by ssvegaraju

Issue #154 , if available:

Description of changes:
Added a size parameter to the multisearch used by the inclusion parameters (include and revinclude). Updated test snapshots to include the size parameter.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-31 20:17 UTC, carvantes requested changes
Solution is correct. I left a couple of comments to tidy up the implementation.

Also, consider renaming the PR. Something like "fix: allow revinclude to return more than 10 resources". 
It's often better to think about the end result instead of the specific internals being changed when thinking of a PR name.

2022-01-31 20:17 UTC, carvantes commented on src/elasticSearchService.ts
> +                { query: query.body!.query, ...{ size: 1000 } },
Create a constant for the `1000`

Also, I think that we should make this change somewhere else. This is the `executeQueries` method and it is misleading that it is modifying queries before executing them. I think that we should make the change where the queries are being built. e.g. https://github.com/awslabs/fhir-works-on-aws-search-es/blob/9847e1415d5067496b391e733fdd365185a062f0/src/searchInclusions.ts#L175

2022-02-01 01:20 UTC, ssvegaraju commented on src/elasticSearchService.ts
> +                { query: query.body!.query, ...{ size: 1000 } },
I implemented `size` into the inclusion queries, and double checked that any queries made without a `size` parameter would still work as before with the changes made to `executeQueries()`. Not sure if MAX_NUM_ES_HITS is an appropriate name for the constant, however.

2022-02-01 01:50 UTC, carvantes commented on src/constants.ts
> +export const MAX_NUM_ES_HITS: number = 1000;
this const is specific to inclusion params. Maybe rename to `MAX_INCLUSION_PARAM_RESULTS`

2022-02-01 01:50 UTC, carvantes commented on src/elasticSearchService.ts
> +                { query: query.body!.query, ...{ size: 1000 } },
Looks good. I just left a minor comment with a name suggestion for the constant

2022-02-01 02:03 UTC, ssvegaraju commented on src/constants.ts
> +export const MAX_NUM_ES_HITS: number = 1000;
Thank you for the name suggestion, I've updated it as such!

2022-02-01 02:05 UTC, carvantes approved these changes

2022-02-01 02:10 UTC, merged