refactor: Don't start iterative inclusion search if there are no iterative inclusion parameters
awslabs/fhir-works-on-aws-search-es pull request #20
Opened 2020-10-13 20:17 UTC by nguyen102

Description of changes:
Don't start iterative inclusion search if there are no iterative inclusion parameters

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-10-13 20:25 UTC, rsmayda commented on src/elasticSearchService.ts
> +            }).length === 0
nitpick: I think `some` is clearer:  `arr1.some(r=> arr2.includes(r))`

2020-10-13 20:58 UTC, nguyen102 commented on src/elasticSearchService.ts
> +            }).length === 0
updated

2020-10-13 23:15 UTC, carvantes requested changes

2020-10-13 23:15 UTC, carvantes commented on src/elasticSearchService.ts
> +                return Object.keys(request.queryParams).includes(param);
Just access queryParams by key instead of doing .includes on the array of keys

2020-10-14 00:25 UTC, nguyen102 commented on src/elasticSearchService.ts
> +                return Object.prototype.hasOwnProperty.call(request.queryParams, param);
Using `Object.prototype.hasOwnProperty.call` as per eslint's suggestion https://eslint.org/docs/rules/no-prototype-builtins

2020-10-14 00:36 UTC, nguyen102 commented on src/elasticSearchService.ts
> +                return Object.keys(request.queryParams).includes(param);
updated

2020-10-14 16:21 UTC, carvantes commented on src/elasticSearchService.ts
> +                return Object.prototype.hasOwnProperty.call(request.queryParams, param);
why are we using `Object.prototype.hasOwnProperty` instead of just checking `queryParams [param]` ?

2020-10-14 17:02 UTC, nguyen102 commented on src/elasticSearchService.ts
> +                return Object.prototype.hasOwnProperty.call(request.queryParams, param);
Ah good question. 

Using `queryParams[param]` could introduce a subtle bug. Example shown below
```
var obj = { key: undefined };
obj["key"] !== undefined // false, but the key exists!

2020-10-14 17:22 UTC, nguyen102 commented on src/elasticSearchService.ts
> +                return Object.prototype.hasOwnProperty.call(request.queryParams, param);
Ah good question. 

Using `queryParams[param]` could introduce a subtle bug. Example shown below
```
var obj = { key: undefined };
obj["key"] !== undefined // false, but the key exists!
```
Granted it might not be possible for this particular variable, `queryParams[param]` to be explicitly defined as `undefined` when a user make a search request.  However, I don't think it hurts to use `hasOwnProperty` to be extra safe. 

More details in this [link](https://stackoverflow.com/a/1098955)

2020-10-14 19:07 UTC, carvantes commented on src/elasticSearchService.ts
> +                return Object.prototype.hasOwnProperty.call(request.queryParams, param);
Code is correct, but find it misleading:
- It implies that this function cares about the difference between a missing key and a key with value of undefined. It doesn't, they are the same for this function, there's no subtle bug here.
- It implies that we are giving special treatment to inherited properties. We aren't. This isn't too relevant since as you mention `queryparams` is expected to be a simple object generated by Express. Even then, if we consider a weird case where queryparams inherited the `_include:iterate` property, we probably should be reading that inherited property.

2020-10-14 19:47 UTC, nguyen102 commented on src/elasticSearchService.ts
> +                return Object.prototype.hasOwnProperty.call(request.queryParams, param);
updated

2020-10-14 20:56 UTC, carvantes approved these changes

2020-10-14 23:19 UTC, merged