feat: Implement date prefix based search
awslabs/fhir-works-on-aws-search-es pull request #28
Opened 2020-12-10 18:02 UTC by PrimKruskal

Issue #, if available:
Description of changes:

These PR adds support to search based on dates and its prefixes 

From the FHIR spec:
https://www.hl7.org/fhir/search.html

A date parameter searches on a date/time or period. As is usual for date/time related functionality, while the concepts are relatively straight-forward, there are a number of subtleties involved in ensuring consistent behavior.

The date parameter format is yyyy-mm-ddThh:mm:ss[Z|(+|-)hh:mm] (the standard XML format).

**Prefixes:**
eq | the value for the parameter in the resource is equal to the provided value | the range of the search value fully contains the range of the target value
-- | -- | --
ne | the value for the parameter in the resource is not equal to the provided value | the range of the search value does not fully contain the range of the target value
gt | the value for the parameter in the resource is greater than the provided value | the range above the search value intersects (i.e. overlaps) with the range of the target value
lt | the value for the parameter in the resource is less than the provided value | the range below the search value intersects (i.e. overlaps) with the range of the target value
ge | the value for the parameter in the resource is greater or equal to the provided value | the range above the search value intersects (i.e. overlaps) with the range of the target value, or the range of the search value fully contains the range of the target value
le | the value for the parameter in the resource is less or equal to the provided value | the range below the search value intersects (i.e. overlaps) with the range of the target value or the range of the search value fully contains the range of the target value
sa | the value for the parameter in the resource starts after the provided value | the range of the search value does not overlap with the range of the target value, and the range above the search value contains the range of the target value
eb | the value for the parameter in the resource ends before the provided value | the range of the search value does overlap not with the range of the target value, and the range below the search value contains the range of the target value

Other changes 
ap - Approximation changes is not yet implemented. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-12-11 16:35 UTC, nguyen102 commented on src/constants.ts
> +export const DATEFIELDS = [
Nitpick: Can we make these constants `SNAKE_CASE`? Example, `DATE_FIELDS`

2020-12-11 16:39 UTC, nguyen102 commented on src/constants.ts
> +    NOTEQUAL = 'ne',
Nitpick: `NOT_EQUAL`

2020-12-11 16:39 UTC, nguyen102 commented on src/constants.ts
> +    LESSEROREQUAL = 'lte',
Nitpick: `LESS_OR_EQUAL`

2020-12-11 16:39 UTC, nguyen102 commented on src/elasticSearchService.ts
> +            console.log(JSON.stringify(params));
Debugging statement? Should we delete this?

2020-12-11 18:29 UTC, carvantes requested changes
Hi, 

Thanks for submitting the PR.

Aside from the comments I left in the code, you should also add unit tests for the new functionality. The easiest would be to add tests on `elasticSearchService.test.ts` that cover search queries with dates/prefixes. Tests would be similar to the existing ones and rely on snapshots.

2020-12-11 18:29 UTC, carvantes commented on src/__snapshots__/elasticSearchService.test.ts.snap
> -            ],
This is a bug. Queries must filter using the `filterRulesForActiveResources` clause

btw, if you are not familiar with snapshot tests, the idea is that snapshots should not change unless we are explicitly changing the functionality. I'd expect your changes on this PR should to have none or minimal changes on the existing snapshots since the way we handle dates shouldn't affect the existing queries for non-date fields

https://jestjs.io/docs/en/snapshot-testing

2020-12-11 18:29 UTC, carvantes commented on src/queryBuilder.ts
> +        for (const prefix of ALLOWED_PREFIXES) {
Using `for of` is discouraged. Use `ALLOWED_PREFIXES.forEach` instead

2020-12-11 18:29 UTC, carvantes commented on src/queryBuilder.ts
> +            if (value.includes(prefix)) {
looks like a bug, what if the value includes prefix but not at the starting position? i.e. "some**eq**stringvalue"

2020-12-11 18:29 UTC, carvantes commented on src/queryBuilder.ts
> +/* eslint-disable class-methods-use-this */
Let's not do this.

As it stands now, I don't think the `QueryBuilder` should be a class. It has a single public method and its state is not complex and it's just acting as a parameter to the single public method.

I think that this module could simply export a function like:
```
buildQuery(queryParams: any): any
```

2020-12-14 12:37 UTC, PrimKruskal commented on src/constants.ts
> +export const DATEFIELDS = [
Thank u nguyen. I have made it as snake case.

2020-12-14 12:38 UTC, PrimKruskal commented on src/constants.ts
> +    NOTEQUAL = 'ne',
Thank u nguyen. I have made it as snake case.

2020-12-14 12:38 UTC, PrimKruskal commented on src/constants.ts
> +    LESSEROREQUAL = 'lte',
Thank u nguyen. I have made it as snake case.

2020-12-14 12:38 UTC, PrimKruskal commented on src/elasticSearchService.ts
> +            console.log(JSON.stringify(params));
Thank u nguyen. I have removed it.

2020-12-14 12:39 UTC, PrimKruskal commented on src/queryBuilder.ts
> +        for (const prefix of ALLOWED_PREFIXES) {
Thank u Cervantes. I have converted to FOR loop, so that we can break once first prefix is found.

2020-12-14 12:44 UTC, PrimKruskal commented on src/queryBuilder.ts
> +            if (value.includes(prefix)) {
Thank u Carvantes. As per FHIR standard, date fields will always have prefixes at starting. Now I have handled in a way to ignore if we found prefix other than starting position and considered entire value to part of search string. 
In future while implementing for string,  there won't be search based on value prefix. For string search, we will be having only parameter prefixes like name:contains=eve or name:exact=Eve. 

Kindly correct me, if my understanding is incorrect.

2020-12-14 12:44 UTC, PrimKruskal commented on src/queryBuilder.ts
> +/* eslint-disable class-methods-use-this */
Thanks Carvantes. Converted into a function.

2020-12-14 12:46 UTC, PrimKruskal commented on src/__snapshots__/elasticSearchService.test.ts.snap
> -            ],
Thanks Carvantes.  I have added snapshots but I am not sure whether I have completely addressed your comments.  Kindly check the latest commit and let me know if I need to make any other changes.

2020-12-16 19:09 UTC, carvantes requested changes

2020-12-16 19:09 UTC, carvantes commented on src/elasticSearchService.test.ts
> +            expect((ElasticSearch.search as jest.Mock).mock.calls).toMatchSnapshot('msearch queries');
Remove this line 427. Only the _include/_revinclude use msearch queries

2020-12-16 19:21 UTC, carvantes commented on src/__snapshots__/elasticSearchService.test.ts.snap
> -            ],
The latest commit still has the same bug. The snapshot is telling us that a filter clause was removed from existing queries, and that's not what we want.

Queries are missing the `filterRulesForActiveResources` at https://github.com/awslabs/fhir-works-on-aws-search-es/blob/mainline/src/elasticSearchService.ts#L39 clause.

`filterRulesForActiveResources` is a filter that must be present on ALL queries in addition to any clauses that are derived from the search parameters. It is a user provided filter to filter out non-searchable documents. It is useful for soft-deleting documents. 
On the actual implementation the filter is:`[{ match: { documentStatus: 'AVAILABLE' } }]` . On the unit tests the filter is `[{ match: { someFieldThatTellsIfTheResourceIsActive: 'AVAILABLE' } }],`

It shouldn't be too hard to fix, just make sure that your `buildQuery` method always adds a filter clause with the value of `filterRulesForActiveResources`

2020-12-16 20:07 UTC, carvantes requested changes

2020-12-16 20:07 UTC, carvantes commented on src/queryBuilder.ts
> +        return { typeOfQuery: TYPE_OF_QUERY.MUST_NOT, query };
I believe this is a bug. Why does `PREFIXES.EQUAL` ends up on the `must_not` clause. I believe that no prefix is equivalent to the `eq` prefix

i.e. both are the same:
```
{{API_URL}}/Patient?birthdate=2003-12-03
{{API_URL}}/Patient?birthdate=eq2003-12-03
```

2020-12-17 21:33 UTC, PrimKruskal commented on src/elasticSearchService.test.ts
> +            expect((ElasticSearch.search as jest.Mock).mock.calls).toMatchSnapshot('msearch queries');
Thanks Carvantes. Removed search now.

2020-12-17 21:33 UTC, PrimKruskal commented on src/queryBuilder.ts
> +        return { typeOfQuery: TYPE_OF_QUERY.MUST_NOT, query };
Guess morning coffee didn't kick when I coded that line.  Fixed the issue now. Thanks

2020-12-17 21:35 UTC, PrimKruskal commented on src/__snapshots__/elasticSearchService.test.ts.snap
> -            ],
My bad. I should have captured earlier. I fixed this now. I added additional check to check for length of Filter.  If we have filter available and es is not allowing to add an empty array.  I tested multiple scenarios as well.

2020-12-22 23:03 UTC, carvantes requested changes

2020-12-22 23:03 UTC, carvantes commented on src/queryBuilder.ts
> +    if (filterRulesForActiveResources.length > 0) filter.push(filterRulesForActiveResources);
There's still an unintended change on the snapshots. the `filter` is now an array of arrays of query objects instead of an array of  query objects. The query itself is valid, but it's better to avoid an unnecessary nested array.

I believe that the following change + regenerating the snapshots should fix it:

```suggestion
    if (filterRulesForActiveResources.length > 0) filter.push(...filterRulesForActiveResources);
```

2020-12-22 23:05 UTC, carvantes commented on src/__snapshots__/elasticSearchService.test.ts.snap
>              ],
This should not change to a nested array. See my other comment on the `buildQuery` function

2020-12-23 17:11 UTC, PrimKruskal commented on src/queryBuilder.ts
> +    if (filterRulesForActiveResources.length > 0) filter.push(filterRulesForActiveResources);
Thanks Carvantes. Fixed the issue. Happy Christmas !!!

2020-12-23 17:11 UTC, PrimKruskal commented on src/__snapshots__/elasticSearchService.test.ts.snap
>              ],
Thanks Carvantes. Fixed the issue. Happy Christmas !!!

2021-02-22 19:03 UTC, PrimKruskal commented
Deleting the pull request.

2021-02-22 19:03 UTC, closed without merging